//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foglalasok
    {
        public int FoglalasokSK { get; set; }
        public int UgyfelekFK { get; set; }
        public System.DateTime Kezdete { get; set; }
        public System.DateTime Vege { get; set; }
        public int GepjarmuFK { get; set; }
    
        public virtual Gepjarmu Gepjarmu { get; set; }
        public virtual Ugyfelek Ugyfelek { get; set; }
    }
}
