//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeadandóEntities : DbContext
    {
        public BeadandóEntities()
            : base("name=BeadandóEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Foglalasok> Foglalasok { get; set; }
        public virtual DbSet<Gepjarmu> Gepjarmu { get; set; }
        public virtual DbSet<Serulesek> Serulesek { get; set; }
        public virtual DbSet<TipusAr> TipusAr { get; set; }
        public virtual DbSet<Ugyfelek> Ugyfelek { get; set; }
    }
}
