//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serulesek
    {
        public int SerulesSK { get; set; }
        public int GepjarmuFK { get; set; }
        public string Helye { get; set; }
        public string Tipusa { get; set; }
    
        public virtual Gepjarmu Gepjarmu { get; set; }
    }
}
